Numpy is "Numericl Python"
All the computation with arrays ,matrix can be done using Numpy
Real time applications of Numpy : In the field of Data Science ,where we deal with Images,which is stored as a matrix..we use numpy module to do the Computations

Understanding of 1D,2D,3D arrays in numpy

In [15]:
import numpy as np

Creating a 1d array using numpy

In [16]:
#creating a 1d array using numpy
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


Type is returned as ndarray..Its a n-dimensional array

In [17]:
type(arr1)

numpy.ndarray

To get the shape of arr1

In [26]:
arr1.shape

(5,)

Creating a 2d-array

In [18]:
##Creating a 2d_array

In [43]:
arr2=np.array([[1,2],[3,4]])

In [20]:
arr2

array([[1, 2],
       [3, 4]])

In [21]:
type(arr2)

numpy.ndarray

In [14]:
arr2.ndim

2

Get the shape of the Array

In [27]:
arr2.shape #2,2 --> 2rows and 2 columns

(2, 2)

get the

Creating a 3d-array

In [22]:
arr3=np.array([[[1,3],[4,7]],[[2,4],[5,7]]])

In [23]:
type(arr3)

numpy.ndarray

In [24]:
arr3

array([[[1, 3],
        [4, 7]],

       [[2, 4],
        [5, 7]]])

In [13]:
arr3.ndim

3

Get the shape of the Array

In [28]:
arr3.shape #Always read from the end..it says 2row and 2cols==>[[1,3],[4,7]],[[2,4],[5,7]]..How many such elemnts are there ---> it is 2..which is the 3rd number reading from the right side.
           #It is 2 matrixs of size (2*2)

(2, 2, 2)

In [ ]:
# Below is another example of 3darray

In [29]:
arr4=np.array([[[1,3],[4,7]],[[2,4],[5,7]],[[12,16],[20,22]]])

In [30]:
arr4.shape##Here we can see that it has 2rows and 2cols,and 3rd element from the right is Number of such elements.


(3, 2, 2)

Difference between the functionalities of arange() and linspace ()  in numpy

arange function - This will give the values in the matrix in thespecified range.By default values will increase by 1

In [ ]:
np.arange(1,9)

arange function - This will give the values in the matrix in thespecified range.Here the value is increasing  by 2

In [ ]:
np.arange(1,9,2)

linspace function - This function will give the values in the matrix in the specified range with even distribution .Example:(1,9,5)==> 1-start element 9-Ending range element,5--Number of elements.. linspace divides in equal space

In [33]:
np.linspace(1,9,5)

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

Difference between shallowcopy() and deepcopy()
shallowcopy -- will point to the same address..hence the change in the original array arr2..reflects the change in the assigned array shallowArr.
deepcopy---here the newly assigned array will point to the diffferent address,hence the change in the original array is not seen in the assigned array

Ex: shallowArr=arr2--> here shallowArr and arr2 are pointing to the same addres.hence any change to the array arr2 will affect the shallowArr and the changes are seen

deepArr=np.copy(arr2)--->here deepArr and arr2 are pointing to the different addres.hence any change to the array arr2 will not affect the deepArr and hence the changes are not seen in deepArr

In [44]:
shallowArr=arr2

In [45]:
deepArr=np.copy(arr2)

In [46]:
arr2[0][0] =5

In [47]:
arr2

array([[5, 2],
       [3, 4]])

In [48]:
shallowArr

array([[5, 2],
       [3, 4]])

In [49]:
deepArr

array([[1, 2],
       [3, 4]])

fromfunction in numpy
Here fromfunction creates a matrix of size 4*4 using a lambda function : multiplying the row and col-index

In [50]:
np.fromfunction(lambda i,j:i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

fromfunction in numpy
Here fromfunction creates a matrix of size 4*4 using a lambda function : adding the row and col-index

In [52]:
np.fromfunction(lambda i,j:i+j,(4,4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

fromfunction in numpy
Here fromfunction creates a matrix of size 4*4 using a lambda function : check and return True or False whenever the diagnoal is equal

In [53]:
np.fromfunction(lambda i,j:i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

fromfunction in numpy array can also use actual elements

Create an Identity matrixwith primary diagonal =1 is created using eye() function.

In [55]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Reshape function in Numpy

In [56]:
dataset=np.linspace(2,9,50)#this creates a dataset with 50 elements in between 2-9 with even space

In [57]:
dataset

array([2.        , 2.14285714, 2.28571429, 2.42857143, 2.57142857,
       2.71428571, 2.85714286, 3.        , 3.14285714, 3.28571429,
       3.42857143, 3.57142857, 3.71428571, 3.85714286, 4.        ,
       4.14285714, 4.28571429, 4.42857143, 4.57142857, 4.71428571,
       4.85714286, 5.        , 5.14285714, 5.28571429, 5.42857143,
       5.57142857, 5.71428571, 5.85714286, 6.        , 6.14285714,
       6.28571429, 6.42857143, 6.57142857, 6.71428571, 6.85714286,
       7.        , 7.14285714, 7.28571429, 7.42857143, 7.57142857,
       7.71428571, 7.85714286, 8.        , 8.14285714, 8.28571429,
       8.42857143, 8.57142857, 8.71428571, 8.85714286, 9.        ])

In [59]:
dataset.shape #an 1-D array is created

(50,)

To convert the above 1-D array to 2-D array we use reshape function numpy.
Always make sure that the reshaped size of the  elemnts in the array should be equal to the original array

In [60]:
dataset.reshape(2,1,25)  #here it is creating 2 different matrices of size (1,25)==> totally it should be equal to 50: 2*1*25=50

array([[[2.        , 2.14285714, 2.28571429, 2.42857143, 2.57142857,
         2.71428571, 2.85714286, 3.        , 3.14285714, 3.28571429,
         3.42857143, 3.57142857, 3.71428571, 3.85714286, 4.        ,
         4.14285714, 4.28571429, 4.42857143, 4.57142857, 4.71428571,
         4.85714286, 5.        , 5.14285714, 5.28571429, 5.42857143]],

       [[5.57142857, 5.71428571, 5.85714286, 6.        , 6.14285714,
         6.28571429, 6.42857143, 6.57142857, 6.71428571, 6.85714286,
         7.        , 7.14285714, 7.28571429, 7.42857143, 7.57142857,
         7.71428571, 7.85714286, 8.        , 8.14285714, 8.28571429,
         8.42857143, 8.57142857, 8.71428571, 8.85714286, 9.        ]]])